# theme: cayman
# theme: ockham
theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0

#theme: architect
plugins:
  - jekyll-remote-theme

    #remote_theme: vfvong/jekyll-theme-tao

title: [Are we facing a climate change awareness pandemic ?]
description: [A template website for ADA]
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: About
    url: about
