plugins:
  - jekyll-remote-theme

# remote_theme: daviddarnes/alembic@main

theme: jekyll-theme-architect


title: "Are we facing a climate change awareness pandemic ?"
description: "A template website for ADA"

# Site settings

# hide left sidebar
sidebar: false
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: About
    url: about
