theme: jekyll-theme-minimal
# theme: ockham

#theme: architect
plugins:
  - jekyll-remote-theme

    #remote_theme: vfvong/jekyll-theme-tao

title: Are we facing a climate change awareness pandemic ?
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: About
    url: about
