theme: jekyll-theme-minimal
# theme: ockham

# remote_theme: vfvong/jekyll-theme-tao

plugins:
  - jekyll-remote-theme
title: Are we facing a climate change awareness pandemic ?
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
